
server:
    port: 8086

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0

spring:
    application:
        name: api-gateway
    config:
        import: "optional:configserver:http://localhost:8088/"
      
    cloud:
        gateway:
            routes:
            - id: employee-service
              uri: lb://employee-service
              predicates:
                - Path=/employees/**

            - id: department-service
              uri: lb://department-service
              predicates:
                - Path=/departments/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            
            - id: payement-service
              uri: lb://payement-service
              predicates:
                - Path=/api/payments/**,/api/paymentmethods/**,/api/applications/**

                
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/traders/**

            # Configuration des paramètres pour accepter le cors origin
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE



