

server:
    port: 8085

spring:
    application:
        name: account-service

    config:
        import: "optional:configserver:http://localhost:8088/"

    cloud:
        config:
            enabled: false

    main:
        allow-bean-definition-overriding: true

    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            query:
                plan_cache_max_size: 64
                plan_parameter_metadata_max_size: 32
                
    datasource:
        url: jdbc:postgresql://localhost:5432/pline_pay_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
        username: plinepay
        password: plinepay
        hikari:
            maximum-pool-size: 10
        driverClassName: org.postgresql.Driver

springdoc:
    api-docs:
        path: /docs/account
